"""The entity-extractor interface, and the one helper that builds Mentions.

WHY AN INTERFACE
----------------
We will run THREE different extractors over the same text:
  1. a spaCy statistical model  (fast, 18 types)
  2. a transformer model        (more accurate, 4 types)
  3. a gazetteer + rules        (supplies COUNTRY and ROLE, which no
                                 off-the-shelf model provides)

They have nothing in common internally, but they all answer the same question:
"given this document, which spans are entities?" A shared Protocol lets the
merge step treat them uniformly, and lets config decide which ones run.

WHY ONE SHARED MENTION BUILDER
------------------------------
``build_mention`` is the ONLY place a Mention gets constructed. Every extractor
must go through it. That guarantees, for all of them at once:
  * the surface text really is document.text[start:end] (no drift),
  * sentence_index is looked up the same way,
  * mention IDs are generated by the same deterministic rule,
  * offsets are validated before a bad span escapes into the pipeline.

If each extractor built its own Mentions, these rules would drift apart and you
would get bugs that appear with one extractor and not another.
"""

from __future__ import annotations

from typing import Protocol, Sequence, runtime_checkable

from src.logging_utils import get_logger
from src.schemas import Document, Mention, make_mention_id

logger = get_logger(__name__)


@runtime_checkable
class EntityExtractor(Protocol):
    """Anything that can find entity mentions in a document."""

    name: str

    def extract(self, document: Document) -> list[Mention]:
        ...

    def extract_batch(self, documents: Sequence[Document]) -> list[list[Mention]]:
        ...


class OffsetError(ValueError):
    """Raised when a proposed mention span is not valid for the document."""


def build_mention(
    document: Document,
    start: int,
    end: int,
    label: str,
    raw_label: str,
    score: float,
    extractor: str,
    model_version: str = "",
) -> Mention:
    """Construct a validated Mention. The single entry point for all extractors.

    Raises OffsetError on an impossible span rather than silently clamping it.
    A silently clamped span is a mention pointing at the wrong words, which
    produces a wrong entity and a wrong relation, with nothing in the logs.
    """
    if start < 0 or end > len(document.text):
        raise OffsetError(
            f"span ({start},{end}) outside text of length {len(document.text)} "
            f"for article {document.article_id}"
        )
    if start >= end:
        raise OffsetError(f"empty or inverted span ({start},{end})")

    surface = document.text[start:end]

    sentence = document.sentence_containing(start)
    sentence_index = sentence.index if sentence else -1

    return Mention(
        mention_id=make_mention_id(document.article_id, start, end, label),
        article_id=document.article_id,
        start=start,
        end=end,
        text=surface,
        label=label,
        raw_label=raw_label,
        # Clamp to [0,1]: rule-based extractors hand us hand-picked constants
        # and a typo of 1.5 would silently outrank every model prediction.
        score=max(0.0, min(1.0, float(score))),
        sentence_index=sentence_index,
        extractor=extractor,
        model_version=model_version,
    )


# Entity-final abbreviations whose trailing period is part of the NAME.
# "Morgan Stanley Inc" and "Morgan Stanley Inc." must not become two different
# surface forms, so the period is kept rather than trimmed.
_ENTITY_FINAL_ABBREVIATIONS = {
    "inc", "ltd", "co", "corp", "plc", "pvt", "llc", "llp", "bros",
    "jr", "sr", "st", "mt",
}


def _ends_with_abbreviation(text: str, end: int) -> bool:
    """True if the period at ``end - 1`` belongs to an abbreviation.

    Two accepted cases:
      * a single capital letter before the dot -- "U.S.", "S." (an initial);
      * a known entity-final abbreviation -- "Inc.", "Ltd.".
    """
    if end - 2 < 0 or text[end - 1] != ".":
        return False
    if text[end - 2].isupper() and (end - 3 < 0 or not text[end - 3].isalpha()):
        return True

    cursor = end - 1
    while cursor > 0 and text[cursor - 1].isalpha():
        cursor -= 1
    return text[cursor : end - 1].lower() in _ENTITY_FINAL_ABBREVIATIONS


def trim_span(text: str, start: int, end: int) -> tuple[int, int]:
    """Shrink a span past leading/trailing whitespace and stray punctuation.

    Models routinely return spans with a trailing space or a possessive, e.g.
    "Modi 's" or "Reliance ". Left alone, "Modi" and "Modi " become two
    different surface forms and therefore two candidate entities in Phase 6 --
    so this small cleanup prevents a real entity-resolution bug.

    Note we trim only characters that cannot begin or end a name. We do NOT
    strip interior punctuation: "U.S." and "Morgan Stanley Inc." need theirs.
    """
    # A leading period is always junk: no name begins with one. This showed up
    # as the mention ". Jaishankar" from "Dr. S. Jaishankar", which then became
    # the subject of a relation.
    while start < end and (text[start].isspace() or text[start] in "\"'(-,."):
        start += 1
    while end > start and (text[end - 1].isspace() or text[end - 1] in "\"')-,."):
        # Keep a trailing period that belongs to an abbreviation ("Inc.",
        # "U.S."), because it is part of the entity's name rather than
        # sentence punctuation.
        if text[end - 1] == "." and _ends_with_abbreviation(text, end):
            break
        end -= 1
    return start, end


def verify_mentions(document: Document) -> list[str]:
    """Check that every stored mention still matches the document text.

    This is the denormalisation tripwire. ``Mention.text`` is a copy of
    ``document.text[start:end]``; if the two ever disagree, offsets are stale
    and every downstream result for this article is wrong while nothing crashes.
    """
    problems: list[str] = []
    for mention in document.mentions:
        if mention.end > len(document.text) or mention.start < 0:
            problems.append(f"{mention.mention_id}: span outside document bounds")
            continue
        actual = document.text[mention.start : mention.end]
        if actual != mention.text:
            problems.append(
                f"{mention.mention_id}: stored text {mention.text!r} != actual {actual!r}"
            )
    return problems
