"""Assemble a HuggingFace Space deployment folder.

    python scripts/prepare_space.py            # full profile (16 GB Space)
    python scripts/prepare_space.py --lite     # lite profile (smaller/faster)

WHY A BUILD STEP INSTEAD OF "JUST PUSH THE REPO"
------------------------------------------------
Three things differ between this repository and what a Space needs, and each
one fails in a confusing way if you skip it:

1. README.md IS CONFIG ON A SPACE. HuggingFace reads YAML frontmatter from
   README.md to decide the SDK, the entry point and the hardware. Our README is
   documentation. Pushing it as-is gives you a Space that will not start, with
   an error that does not mention the README.

2. THE FILE MUST BE NAMED requirements.txt. Spaces install exactly that path.
   Our full profile lives in requirements-full.txt, and `-r requirements.txt`
   indirection is fragile here, so we FLATTEN both files into one.

3. spaCy MODELS CANNOT BE INSTALLED WITH `python -m spacy download`. There is no
   post-install hook on a Streamlit Space, so the model has to arrive as a
   pip-installable wheel URL inside requirements.txt.

The script also excludes what must never be pushed: the virtualenv, the SQLite
database, caches, and .env.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BUILD_DIR = PROJECT_ROOT / "build" / "space"

# Copied wholesale. data/sample is included so the Space has the demo corpus and
# the gold set; data/raw and data/processed are derived and are not.
INCLUDE_DIRS = ["src", "config", "docs"]
INCLUDE_FILES = ["pyproject.toml", "app.py"]
INCLUDE_DATA = ["data/sample"]

EXCLUDE_PATTERNS = shutil.ignore_patterns(
    "__pycache__", "*.pyc", "*.pyo", ".pytest_cache", "*.db", "*.sqlite3",
    ".venv", ".env", "*.egg-info",
)

SPACE_README = """---
title: News Knowledge Graph
emoji: 🕸️
colorFrom: blue
colorTo: indigo
sdk: gradio
sdk_version: 6.10.0
app_file: app.py
pinned: false
license: mit
short_description: Extract entities, relations and a knowledge graph from news
---

# 🕸️ News Knowledge Graph

Paste news article URLs and get back a queryable knowledge graph: people,
organisations, countries, roles, events, and the relations between them —
resolved into canonical entities **across** articles, with every fact traceable
to the sentence it came from.

```
articles → clean & segment → NER → coreference → relations
                                                    ↓
                      query ← knowledge graph ← entity resolution
```

The point of the pipeline is that last step. Given three articles saying
"Narendra Modi", "PM Modi" and "the Indian Prime Minister", it decides they are
one person — while keeping **Lalit Modi**, a different person who shares the
surname, separate. That second half is the hard part, and it is why the system
uses hard vetoes and a human review queue rather than one similarity score.

## Profiles

| | `lite` (default here) | `full` |
|---|---|---|
| NER | spaCy + gazetteer | + BERT transformer |
| Coreference | rule-based | LingMess neural (590M) |
| Entity resolution | strings + attributes | + context embeddings |
| Speed | <1 s/article | ~14 s/article on CPU |

This Space runs **lite**, which needs no GPU and no large downloads. Its
measured cost: it resolves **no nominal coreference**, so "The Indian Prime
Minister" never links to Modi and the relations depending on that link are lost.
Run `full` locally to see the difference.

## Notes

- **No API keys needed.** All models are public; there is no LLM in the pipeline.
- Large publishers (Reuters, Bloomberg) block scraping — use the **Paste raw
  text** box, or try Wikipedia and regional outlets.
- Evaluation scores come from **3 hand-labelled articles, one annotator**.
  A development signal, not a benchmark.

Built as a teaching project — every design decision, tradeoff and known
limitation is documented in the module docstrings.
"""

BASE_REQUIREMENTS = """# Generated by scripts/prepare_space.py -- do not edit by hand.
# HuggingFace Spaces installs exactly this file, so both profiles are flattened
# into it rather than using `-r` indirection.

# HuggingFace's ZeroGPU builder auto-injects gradio[mcp] as an extra
# dependency, and gradio[mcp]==6.10.0 requires pydantic<=2.12.5. Pinning
# an exact newer version here caused a real ResolutionImpossible error
# (reproduced locally: pip install -r requirements.txt "gradio[mcp]==6.10.0"),
# so this is a RANGE, not an exact pin, specifically to stay compatible
# with whatever extras the Spaces builder adds on top of our file.
pydantic>=2.6,<=2.12.5
PyYAML==6.0.3
python-dotenv==1.0.1
rich==13.9.4
rapidfuzz==3.14.5
numpy==1.26.4
pandas==2.2.3

# spaCy plus its model. The model MUST be a wheel URL: a Streamlit Space has no
# post-install hook, so `python -m spacy download` can never run.
spacy==3.8.7
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl

# Web article extraction.
trafilatura==2.2.0
# REQUIRED: lxml.html.clean moved into its own package. Without this,
# trafilatura fails to import with an error that does not mention trafilatura.
lxml_html_clean==0.4.2

gradio==6.10.0
"""

# Added to the Space README for the full profile. `preload_from_hub` downloads
# models during the BUILD, not on the first request -- which is what stops the
# first visitor from staring at a three-minute spinner.
PRELOAD_BLOCK = """preload_from_hub:
  - dslim/bert-base-NER
  - intfloat/multilingual-e5-small
  - biu-nlp/lingmess-coref
"""

FULL_REQUIREMENTS = """
# --- FULL profile ----------------------------------------------------------
# ~2.5 GB of models. Needs a Space with >= 6 GB RAM; the free CPU basic tier
# (16 GB) is enough.
--extra-index-url https://download.pytorch.org/whl/cpu
# torch MUST be one of ZeroGPU's supported versions or the Space fails with
# CONFIG_ERROR before it even builds -- and it validates this even when the
# app never calls the GPU. Supported at time of writing:
#   2.13.0, 2.12.1, 2.11.0, 2.10.0, 2.9.1, 2.8.0
torch==2.12.1
transformers==4.49.0
fastcoref==2.1.6
"""


def build(lite: bool) -> Path:
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    BUILD_DIR.mkdir(parents=True)

    for name in INCLUDE_DIRS:
        source = PROJECT_ROOT / name
        if source.exists():
            shutil.copytree(source, BUILD_DIR / name, ignore=EXCLUDE_PATTERNS)

    for name in INCLUDE_FILES:
        source = PROJECT_ROOT / name
        if source.exists():
            shutil.copy2(source, BUILD_DIR / name)

    for name in INCLUDE_DATA:
        source = PROJECT_ROOT / name
        if source.exists():
            target = BUILD_DIR / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(source, target, ignore=EXCLUDE_PATTERNS)

    # Empty dirs the pipeline writes into. Git does not track empty
    # directories, so each needs a .gitkeep or the first write fails.
    for name in ["data/raw", "data/processed"]:
        directory = BUILD_DIR / name
        directory.mkdir(parents=True, exist_ok=True)
        (directory / ".gitkeep").touch()

    readme = SPACE_README
    if not lite:
        # Insert preload_from_hub into the YAML block, before its closing "---".
        head, _, tail = readme.partition("\n---\n")
        readme = head + "\n" + PRELOAD_BLOCK + "---\n" + tail
        readme = readme.replace("This Space runs **lite**", "This Space runs **full**")
    (BUILD_DIR / "README.md").write_text(readme, encoding="utf-8")

    requirements = BASE_REQUIREMENTS if lite else BASE_REQUIREMENTS + FULL_REQUIREMENTS
    (BUILD_DIR / "requirements.txt").write_text(requirements, encoding="utf-8")

    # A Space is its own git repo; keep local junk out of it.
    (BUILD_DIR / ".gitignore").write_text(
        "__pycache__/\n*.py[cod]\n*.db\n*.sqlite3\n.env\ndata/raw/*\n"
        "data/processed/*\n!data/**/.gitkeep\n",
        encoding="utf-8",
    )

    return BUILD_DIR


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--lite", action="store_true",
        help="Build the lite profile (no torch/transformers/fastcoref).",
    )
    args = parser.parse_args()

    path = build(lite=args.lite)
    files = sum(1 for _ in path.rglob("*") if _.is_file())
    size_mb = sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / 1e6

    print("=" * 72)
    print(f"Space build ready: {path}")
    print(f"  profile : {'LITE' if args.lite else 'FULL'}")
    print(f"  files   : {files}")
    print(f"  size    : {size_mb:.1f} MB")
    print("=" * 72)
    print("\nNext steps:\n")
    print("  1. Create a Space:  https://huggingface.co/new-space")
    print("       SDK = Gradio,  Hardware = ZeroGPU (the free tier)")
    print("\n  2. Push this folder to it:\n")
    print(f"       cd {path}")
    print("       git init && git branch -M main")
    print("       git remote add origin https://huggingface.co/spaces/<user>/<space>")
    print("       git add -A")
    print('       git commit -m "Deploy news knowledge graph"')
    print("       git push -u origin main")
    print("\n  3. Watch the build logs in the Space's 'Logs' tab.")
    print("     First FULL run downloads ~2.5 GB of models (a few minutes).")


if __name__ == "__main__":
    main()
